name: Deploy to Azure

on:
  workflow_run:
    workflows: ['CI Pipeline']
    types:
      - completed

jobs:
  deploy-infra:
    if: github.event.workflow_run.conclusion == 'success' && github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: infra
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Terraform Init
        run: terraform init

      - name: Terraform Apply
        run: terraform apply -auto-approve
        env:
          ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
          ARM_CLIENT_SECRET: ${{ secrets.AZURE_CLIENT_SECRET }}
          ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
  deploy-frontend:
    runs-on: ubuntu-latest
    needs: deploy-infra
    steps:
      - name: Download Frontend Artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend
          path: frontend/dist

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Get Storage Account Name
        run: echo "STORAGE_ACCOUNT_NAME=$(az storage account list --query '[?contains(name, 'frontendstorage')].name' -o tsv)" >> $GITHUB_ENV

      - name: Upload Files to Static Website
        run: az storage blob upload-batch \
            --account-name ${{ env.STORAGE_ACCOUNT_NAME }} \
            --destination '$web' \
            --source frontend/dist \
            --overwrite
  deploy-backend:
    runs-on: ubuntu-latest
    needs: deploy-infra
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v4
        with:
          name: backend
          path: backend/artifact

      - name: Azure login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}

      - name: Deploy to Azure Functions
        run: az functionapp deployment source config-zip \
              --resource-group paim-app-rg \
              --name paim-app-function \
              --src backend/artifact