name: CI Pipeline

on: push

jobs:
  test-backend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Setup Poetry
        run: pip install --no-cache-dir "poetry==1.8.4"

      - name: Cache Poetry Dependencies
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pypoetry
            ~/.cache/pip
          key: ${{ runner.os }}-poetry-${{ hashFiles('backend/pyproject.toml', 'backend/poetry.lock') }}
          restore-keys: |
            ${{ runner.os }}-poetry-

      - name: Install dependencies
        run: poetry install --no-root --no-interaction --no-ansi

      - name: Run backend tests
        env:
          MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
          MONGO_USER: ${{ secrets.MONGO_USER }}
          MONGO_DATABASE: ${{ secrets.MONGO_DATABASE_DEV }}
          MONGO_URL: ${{ secrets.MONGO_URL }}
          SECRET_KEY: ${{ secrets.SECRET_KEY }}
          REACT_APP_URL: ${{ secrets.REACT_APP_URL }}
          STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
        run: poetry run pytest --maxfail=2 --disable-warnings -q

      - name: Package application
        run: |
          mkdir -p package
          cp -r application domain infrastructure function_app.py host.json pyproject.toml poetry.lock package/
          cd package && zip -r ../backend.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: backend
          path: backend/backend.zip

  frontend:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: frontend
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "npm"
          cache-dependency-path: frontend/package-lock.json

      - name: Install frontend dependencies
        run: npm ci

      - name: Run frontend tests
        run: npm test

      - name: End job if it's not main branch
        if: github.ref == 'refs/heads/main'
        run: exit 0

      - name: Build frontend
        run: npm run build

      - name: Upload Frontend Artifact
        uses: actions/upload-artifact@v4
        with:
            name: frontend
            path: frontend/dist