name: Keep Function Warm

on:
  schedule:
    - cron: '*/5 * * * *'  # Runs every 5 minutes

jobs:
  keep_warm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Find Last Successful Workflow with Backend Url artifact
        id: find_frontend_url_artifact
        run: |
          LATEST_RUN_ID=$(gh run list \
            --workflow "deployment.yaml" \
            --branch main \
            --json databaseId,conclusion \
            --jq '[.[] | select(.conclusion=="success")] | .[].databaseId' | while read RUN_ID; do
              ARTIFACTS=$(gh api repos/:owner/:repo/actions/runs/$RUN_ID/artifacts --jq '.artifacts[].name')
              echo "$ARTIFACTS" | grep -q "backend-url" && echo $RUN_ID && break
            done)
          
          echo "backend_run_id=$LATEST_RUN_ID" >> $GITHUB_OUTPUT
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Deployment URL
        uses: actions/download-artifact@v4
        with:
          name: backend-url
          run-id: ${{ steps.find_backend_url_artifact.outputs.backend_run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}

      - name: Ping Azure Function
        run: |
          curl -s "$(cat frontend_url.txt)"